language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"

script:
  - DEBUG=zyre* npm test

after_success:
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
