language: node_js
node_js: "6"

os: linux
dist: trusty
sudo: false

env:
  - DEBUG=zyre*

before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  - travis_retry npm run coverage

after_success:
  - greenkeeper-lockfile-upload
  - bash <(curl -s https://codecov.io/bash)
  - npm run build:docs

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GH_TOKEN
  on:
    branch: master
