language: node_js

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
      env: DEPLOY=true
    - os: osx
      node_js: "6"

env:
  global:
    - DEBUG=zyre*

script:
  - travis_retry npm run coverage

after_success:
  - 'if [[ $DEPLOY == true ]]; then npm run build:docs; bash <(curl -s https://codecov.io/bash); fi'

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $DEPLOY = true
