language: node_js
node_js: "6"
sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

env:
  global:
    - DEBUG=zyre*

before_install:
  - npm install -g npm@5
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then npm install -g greenkeeper-lockfile@1; fi

before_script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then greenkeeper-lockfile-update; fi

script:
  - travis_retry npm run coverage

after_success:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then greenkeeper-lockfile-upload; fi
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi
  - if [[ $TRAVIS_OS_NAME == "linux" && $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == false ]]; then npm run build:docs; fi

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GH_TOKEN
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = "linux"
